In [2]:
import torch

torch.__version__

'1.10.0+cu111'

pytorch는 1.10.0을 사용 중이었으며,

cu111인 것을 보아 11.1 버전의 CUDA를 사용하고 있다

In [1]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0


In [12]:
!nvidia-smi

Thu Mar 10 01:41:31 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   65C    P0    70W / 149W |    516MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## 텐서(TENSOR)
배열이나 행렬과 매우 유사한 특수한 자료구조<br>
PyTorch에서는 텐서를 사용하여 모델의 입력과 출력, 모델의 매개변수들을 부호화<br>
<br>
GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면 NumPy의 ndarray와 유사<br>
텐서는 자동 미분에 최적화

In [3]:
import torch
import numpy as np

In [11]:
torch.cuda.get_device_name(0)

'Tesla K80'

In [4]:
# 데이터로부터 직접 생성
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data, type(x_data)

(tensor([[1, 2],
         [3, 4]]), torch.Tensor)

In [5]:
# NumPy 배열로부터 생성
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np, type(x_np)

(tensor([[1, 2],
         [3, 4]]), torch.Tensor)

In [6]:
# 다른 텐서로부터 생성
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성 덮어쓰기
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4650, 0.3232],
        [0.4988, 0.3829]]) 



In [7]:
# shape: 텐서의 차원을 나타내는 튜플
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1830, 0.3619, 0.3600],
        [0.9955, 0.5440, 0.5382]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")   # 텐서의 모양
print(f"Datatype of tensor: {tensor.dtype}")    # 텐서의 자료형
print(f"Device tensor is stored on: {tensor.device}")   # 텐서의 저장장치

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [13]:
torch.cuda.is_available()

True

기본적으로 텐서는 CPU에서 생성<br>
.to 메소드 사용시 GPU로 이동 가능<br>
장치 간에 큰 텐서 복사는 많은 시간과 메모리 비용 소모

In [10]:
# GPU가 존재하면 텐서를 이동
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [14]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [17]:
# torch.cat은 주어진 차원에 따라 일련의 텐서 연결 가능
t1 = torch.cat([tensor, tensor, torch.zeros(4,4)], dim = 1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0.],
        [1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0.],
        [1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0.],
        [1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0.]])

In [25]:
# 두 텐서 간의 행렬 곱
y1= tensor@tensor.T
y2 = tensor.matmul(tensor.T)

y1, y2

(tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]), tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]))

In [28]:
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [29]:
# 요소별 곱(element-wise product) 계산
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z1, z2

(tensor([[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]), tensor([[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]))

In [30]:
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [31]:
# 집계(aggregate)
agg = tensor.sum()
agg_item = agg.item()
agg_item, type(agg_item)

(12.0, float)

In [32]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [33]:
# tensor to NumPy array
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [34]:
# t의 변경사항도 n에 반영됨
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [35]:
# NumPy array to tensor
n = np.ones(5)
t = torch.from_numpy(n)
n, t

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

In [36]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
